test1/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace test1.Models
{
    public class Task
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        [DisplayName("Name")]
        public string Text { get; set; }
        public bool Complete { get; set; }
        [DisplayName("Category")]
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Subtask> Subtasks { get; set; }
        public Task()
        {
            Subtasks = new List<Subtask>();
        }
    }
}

test1/Controllers/TaskPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace test1.Models
{
    public class TaskPartialController : Controller
    {
        private ToDoContext db = new ToDoContext();
        public PartialViewResult _GetForCategory(int id)
        {
            ViewBag.CategoryId = id;
            var list = db.Tasks.Where(p => p.CategoryId == id).ToList<Task>();
            return PartialView("_GetForCategory", list);
        }

        [ChildActionOnly]
        public PartialViewResult _TaskForm(int id)
        {
            var task = new Task { CategoryId = id };
            return PartialView("_TaskForm", task);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult _AddTask(Task task)
        {
            task.Date = DateTime.Now;
            db.Tasks.Add(task);
            db.SaveChanges();

            ViewBag.CategoryId = task.CategoryId;
            var list = db.Tasks.Where(p => p.CategoryId == task.CategoryId).ToList<Task>();
            return PartialView("_GetForCategory", list);
        }

    }
}

test1/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using test1.Models;

namespace test1.Controllers
{
    public class TasksController : Controller
    {
        private ToDoContext db = new ToDoContext();

        // GET: Tasks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }
        // GET: Tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Text", task.CategoryId);
            return View(task);
        }

        // POST: Tasks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,Text,Complete,CategoryId")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id=task.Id.ToString() });
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Text", task.CategoryId);
            return View(task);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Task task = db.Tasks.Find(id);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index","Categories");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeStateOfTask([Bind(Include = "Id,Complete")] IEnumerable<test1.Models.Task> task)
        {
            if (task == null)
            {
                return RedirectToAction("Index", "Categories"); ;
            }
            foreach (var item in task)
            {
                var t = db.Tasks.Where(ah => ah.Id == item.Id).Single<Task>();
                t.Complete = task.Where(a => a.Id == t.Id).Single<Task>().Complete;
                db.Entry(t).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index","Categories");
        }
        public ActionResult DeleteDone (int id)
        {
            List<Task> task = db.Tasks.Where(x => x.CategoryId == id && x.Complete == true).ToList();
            db.Tasks.RemoveRange(task);
            db.SaveChanges();
            return RedirectToAction("Index", "Categories");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

test1/Views/TaskPartial/_GetForCategory.cshtml
@model List<test1.Models.Task>

<div id="listOfTaks">
    <h1>List of Tasks</h1>
    @using (Html.BeginForm("ChangeStateOfTask", "Tasks", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="table">
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    @Html.HiddenFor(model => Model[i].Id)
                    <td>
                        @Html.EditorFor(modelItem => Model[i].Complete, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Date)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "Tasks", new { id = Model[i].Id }, new { })
                    </td>
                </tr>
            }
            <tr>
                <td colspan="4">
                    @if (Model.Count != 0)
                    {
                        <input type="submit" value="Save" class="btn btn-default" />

                        @Html.ActionLink("Delete all Done", "DeleteDone", "Tasks", new
               {
                   id = Model.First<test1.Models.Task>().CategoryId
               }, new { })
                    }
                </td>
            </tr>
        </table>
    }
    @using (Ajax.BeginForm("_AddTask", "TaskPartial", new AjaxOptions { UpdateTargetId = "listOfTaks" }))
    {
        @Html.AntiForgeryToken()
        @Html.Action("_TaskForm", "TaskPartial", new { id = ViewBag.CategoryId })
    }
</div>

test1/Views/TaskPartial/_TaskForm.cshtml
@model test1.Models.Task

@Html.HiddenFor(x => x.CategoryId)


<div>
    @Html.LabelFor(x => x.Text, new { htmlAttributes = new { @class = "form-control" } })
    @Html.EditorFor(x => x.Text, new { htmlAttributes = new { @class = "form-control" } })
</div>
<input type="submit" value="Add Task" class="btn btn-default" />