test1/Models/Subtask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace test1.Models
{
    public class Subtask
    {
        public int Id { get; set; }
        [DisplayName("Name")]
        public string Text { get; set; }
        public bool Complete { get; set; }
        public int TaskId { get; set; }
        public virtual Task Task { get; set; }
    }
}

test1/Controllers/SubtasksController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using test1.Models;

namespace test1.Controllers
{
    public class SubtasksController : Controller
    {
        private ToDoContext db = new ToDoContext();

        public PartialViewResult _GetSubtaskFor(int id)
        {
            ViewBag.TaskId = id;
            var list = db.Subtasks.Where(p => p.TaskId == id).ToList<Subtask>();
            return PartialView("_GetSubtaskFor", list);
        }
        [ChildActionOnly]
        public PartialViewResult _SubtasksForm(int id)
        {
            var task = new Subtask { TaskId = id };
            return PartialView("_SubtasksForm", task);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult _AddSubtask(Subtask subt)
        {
            db.Subtasks.Add(subt);
            db.SaveChanges();

            ViewBag.TaskId = subt.TaskId;
            var list = db.Subtasks.Where(p => p.TaskId == subt.TaskId).ToList<Subtask>();
            return PartialView("_GetSubtaskFor",list);
        }
        public ActionResult ChangeStateOfSubtask(IEnumerable<test1.Models.Subtask> subtask)
        {
            var t = new Subtask();
            bool stateOfTask = false;
            foreach (var item in subtask)
            {
                t = db.Subtasks.Where(ah => ah.Id == item.Id).Single<Subtask>();
                t.Complete = subtask.Where(a => a.Id == t.Id).Single<Subtask>().Complete;
                stateOfTask = t.Complete;
                db.Entry(t).State = EntityState.Modified;
            }
            if(stateOfTask == true)
            {
                db.Tasks.Where(ah => ah.Id == t.TaskId).Single<Task>().Complete = stateOfTask;  
            }
            db.SaveChanges();
            return RedirectToAction("Details", "Tasks", new { id= t.TaskId });
        }
        // GET: Tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subtask subtask = db.Subtasks.Find(id);
            if (subtask == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Text", subtask.TaskId);
            return View(subtask);
        }

        // POST: Tasks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Subtask subtask)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subtask).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details","Tasks", new { id=subtask.TaskId.ToString() });
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Text", subtask.TaskId);
            return View(subtask);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subtask sub = db.Subtasks.Find(id);
            if (sub == null)
            {
                return HttpNotFound();
            }
            return View(sub);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subtask sub = db.Subtasks.Find(id);
            db.Subtasks.Remove(sub);
            db.SaveChanges();
            return RedirectToAction("Details", "Tasks", new { id = sub.TaskId.ToString() });
        }
    }
}

test1/Views/Subtasks/Delete.cshtml
@model test1.Models.Subtask

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subtask</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Task.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Task.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complete)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", "Tasks", new { id = Model.TaskId.ToString() }, new { })
        </div>
    }
</div>

test1/Views/Subtasks/Edit.cshtml
@model test1.Models.Subtask

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Subtask</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Complete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Complete)
                    @Html.ValidationMessageFor(model => model.Complete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        @Html.HiddenFor(model => model.TaskId)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details", "Tasks", new { id = Model.TaskId.ToString() }, new { })
</div>

test1/Views/Subtasks/_GetSubtaskFor.cshtml
@model List<test1.Models.Subtask>

<div id="subtaskss">
    <h1>List of Subtask</h1>
    @using (Html.BeginForm("ChangeStateOfSubtask", "Subtasks", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="table">
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    @Html.HiddenFor(model => Model[i].Id)
                    <td>
                        @Html.EditorFor(modelItem => Model[i].Complete, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Text)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Subtasks", new { id = Model[i].Id }, new { }) |
                        @Html.ActionLink("Delete", "Delete", "Subtasks", new { id = Model[i].Id }, new { })
                    </td>
                </tr>
            }

            <tr>
                <td colspan="4">
                    @if (Model.Count != 0)
                    {
                        <input type="submit" value="Save" class="btn btn-default" />
                    }
                </td>
            </tr>
        </table>
    }
    <div>
        @using (Ajax.BeginForm("_AddSubtask", "Subtasks", new AjaxOptions { UpdateTargetId = "subtaskss" }))
        {
            @Html.AntiForgeryToken()
            @Html.Action("_SubtasksForm", "Subtasks", new { id = ViewBag.TaskId })
        }
    </div>
</div>

test1/Views/Subtasks/_SubtasksForm.cshtml
@model test1.Models.Subtask

@Html.HiddenFor(x => x.TaskId)


<div>
    @Html.LabelFor(x => x.Text, new { htmlAttributes = new { @class = "form-control" } })
    @Html.EditorFor(x => x.Text, new { htmlAttributes = new { @class = "form-control" } })
</div>
<input type="submit" value="Add Subtask" class="btn btn-default" />